### ISSUE TITLE
Start-stop doesn't define a startup-policy

### ISSUE THREAD

**Issue by matsimon** [programmfabrik/easydb-documentation#6]
The documentation mentions running all docker containers without using "--restart" which would lead to containers not starting in case of failure or the moment of restarting the docker host. What is your opinion / preference? (See: https://docs.docker.com/engine/reference/run/#restart-policies---restart)

However the other question being if using docker-compose (instea of using docker run) would allow defining dependencies between the containers since the solution needs all containers to be started - and in the proper order - to work.

Looking forward to your feedback. If there is anything I can contribute to improve the documentation in this section, I'd like to provide feedback and improvements where possible.

**Comment by KlausThornProgrammfabrik** [comment]
Dear Mathieu,

thanks for your input.

We recommend --restart=always and have now added this to the instructions in https://docs.easydb.de/en/sysadmin/installation/#start

We also tried docker-compose, it works, but we are not using it any more. The reason is only that we found it too cumbersome to use together with ansible in multi-server environments - one central compose file was far worse than one file per container in the way we use ansible. This disadvantage does not affect most customers.

But the reason you mention - dependencies - does not require docker-compose. Just start/create the containers in any order, they will wait for each other. This was not always the case but in current versions of easydb5 it is working and tested. (To be honest though: if you later restart e.g. the PostgreSQL container you probably need to restart easydb-server and eas containers manually)

It is unlikely that we will include docker-compose in the documentation as it is not needed.

kind regards,
Klaus Thorn

**Comment by moschlar** [comment]
Dear @KlausThornProgrammfabrik - but your Ansible playbooks are not available to customers that perform installation and maintenance themselves (just the roles, I think), so there is a gap between full automation using Ansible and the full manual "execute these commands and write these files" way of the docs that docker-compose could fill.

I understand that you don't want to support that solution after it has been documented, but could you maybe consider having a "contrib" section in the docs that could contain a `docker-compose.yml` file for those who want to use it?

I'll put my `docker-compose.yml` and `.env` here for inspiration:

```ini
SOLUTION=base
BASEDIR=/srv/easydb
```

```yaml
version: '3'

services:

  pgsql:
    container_name: easydb-pgsql
    image: docker.easydb.de/pf/postgresql-11
    networks:
      - easy5net
    restart: always
    volumes:
      - "$BASEDIR/config:/config"
      - "$BASEDIR/pgsql/etc:/etc/postgresql"
      - "$BASEDIR/pgsql/log:/var/log/postgresql"
      - "$BASEDIR/pgsql/var:/var/lib/postgresql"
      - "$BASEDIR/pgsql/backup:/backup"

  elasticsearch:
    container_name: easydb-elasticsearch
    image: docker.easydb.de/pf/elasticsearch
    networks:
      - easy5net
    restart: always
    volumes:
      - "$BASEDIR/config:/config"
      - "$BASEDIR/elasticsearch/var:/var/lib/elasticsearch"

  eas:
    container_name: easydb-eas
    image: docker.easydb.de/pf/eas
    networks:
      - easy5net
    depends_on:
      - pgsql
    restart: always
    volumes:
      - "$BASEDIR/config:/config"
      - "$BASEDIR/eas/lib:/var/opt/easydb/lib/eas"
      - "$BASEDIR/eas/log:/var/opt/easydb/log/eas"
      - "$BASEDIR/eas/tmp:/tmp"

  server:
    container_name: easydb-server
    image: docker.easydb.de/pf/server-$SOLUTION
    networks:
      - easy5net
    depends_on:
      - pgsql
      - elasticsearch
    restart: always
    volumes:
      - "$BASEDIR/config:/config"
      - "$BASEDIR/easydb-server/var:/easydb-5/var"
      - "$BASEDIR/easydb-server/nginx-log:/var/log/nginx"

  webfrontend:
    container_name: easydb-webfrontend
    image: docker.easydb.de/pf/webfrontend
    ports:
      - "80:80"
    networks:
      - easy5net
    depends_on:
      - server
    restart: always
    security_opt:
      - seccomp=unconfined
    volumes:
      - "$BASEDIR/config:/config"

  fylr:
    container_name: easydb-fylr
    image: docker.easydb.de/pf/fylr
    networks:
      - easy5net
    restart: always
    volumes:
      - "$BASEDIR/config:/config"
      - "$BASEDIR/fylr/objectstore:/objectstore"

networks:
  easy5net:
```

Best regards,
Moritz
